import { Ionicons } from '@expo/vector-icons';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AudioModule, RecordingPresets, setAudioModeAsync, useAudioRecorder, useAudioRecorderState } from 'expo-audio';
import * as Speech from 'expo-speech';
import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { learnQueryKey } from '@/features/learn/learn-api';
import { progressQueryKey } from '@/features/progress/progress-api';
import { evaluateSpeakingRecording, fetchSpeaking, generateSpeakingPractice, speakingQueryKey, type SpeakingPractice, type SpeakingResult } from './speaking-api';

const categoryColors:Record<string,string>={'Daily Life':'#146ef5',Travel:'#e6a01d',Office:'#18a67e',Meetings:'#7c5cff',Career:'#ef6c62'};
function Score({label,value,color}:{label:string;value:number;color:string}){return <View className="mr-2 min-w-[46%] flex-1 rounded-2xl bg-[#f3f7fb] p-4"><Text className="text-xs font-bold uppercase text-[#718198]">{label}</Text><Text className="mt-1 text-2xl font-extrabold" style={{color}}>{value}%</Text></View>;}

export function SpeakingScreen(){
  const queryClient=useQueryClient();const speaking=useQuery({queryKey:speakingQueryKey,queryFn:fetchSpeaking});
  const recorder=useAudioRecorder(RecordingPresets.HIGH_QUALITY);const recorderState=useAudioRecorderState(recorder);
  const [practice,setPractice]=useState<SpeakingPractice|null>(null);const [result,setResult]=useState<SpeakingResult|null>(null);const [recordingError,setRecordingError]=useState<string|null>(null);
  const generate=useMutation({mutationFn:generateSpeakingPractice,onMutate:()=>{setPractice(null);setResult(null);setRecordingError(null);},onSuccess:setPractice});
  const evaluate=useMutation({mutationFn:evaluateSpeakingRecording,onSuccess:async(data)=>{setResult(data);await Promise.all([queryClient.invalidateQueries({queryKey:speakingQueryKey}),queryClient.invalidateQueries({queryKey:progressQueryKey}),queryClient.invalidateQueries({queryKey:learnQueryKey})]);}});
  const startRecording=async()=>{setRecordingError(null);const permission=await AudioModule.requestRecordingPermissionsAsync();if(!permission.granted){Alert.alert('Microphone needed','Allow microphone access to practice speaking.');return;}await setAudioModeAsync({playsInSilentMode:true,allowsRecording:true});await recorder.prepareToRecordAsync();recorder.record();};
  const stopRecording=async()=>{const seconds=Math.max(1,Math.round(recorderState.durationMillis/1000));await recorder.stop();const uri=recorder.uri;if(!uri){setRecordingError('The recording could not be saved. Please try again.');return;}evaluate.mutate({sessionId:practice!.sessionId,uri,durationSeconds:seconds});};
  const reset=()=>{setPractice(null);setResult(null);setRecordingError(null);generate.reset();evaluate.reset();};
  if(speaking.isPending)return <SafeAreaView className="flex-1 items-center justify-center bg-[#fff5f3]"><ActivityIndicator size="large" color="#ef6c62"/></SafeAreaView>;
  if(speaking.error)return <SafeAreaView className="flex-1 items-center justify-center bg-[#fff5f3] px-6"><Ionicons name="cloud-offline-outline" size={42} color="#e35d55"/><Text className="mt-4 text-center font-semibold text-[#10233f]">{speaking.error.message}</Text><Pressable className="mt-5 rounded-2xl bg-[#ef6c62] px-6 py-3" onPress={()=>speaking.refetch()}><Text className="font-bold text-white">Try again</Text></Pressable></SafeAreaView>;
  return <SafeAreaView className="flex-1 bg-[#fff5f3]" edges={['top']}><ScrollView contentContainerClassName="px-5 pb-32 pt-4" showsVerticalScrollIndicator={false}>
    <View className="flex-row items-center justify-between"><View><Text className="text-3xl font-extrabold text-[#10233f]">Speak</Text><Text className="mt-1 text-[#718198]">Practice, record and improve</Text></View>{practice?<Pressable className="rounded-full bg-white px-4 py-2" onPress={reset}><Text className="font-bold text-[#ef6c62]">Exit</Text></Pressable>:null}</View>
    {!practice&&!generate.isPending?<>
      <View className="mt-5 overflow-hidden rounded-[30px] bg-[#ef6c62] p-6 shadow-lg shadow-red-200"><View className="absolute -right-8 -top-10 h-36 w-36 rounded-full bg-white/15"/><View className="h-14 w-14 items-center justify-center rounded-2xl bg-white/20"><Ionicons name="mic" size={29} color="white"/></View><Text className="mt-4 text-2xl font-extrabold text-white">Your AI conversation coach</Text><Text className="mt-2 leading-6 text-[#fff0ee]">Choose a real situation, speak for 30–90 seconds, and receive useful feedback on grammar, vocabulary, flow and relevance.</Text></View>
      <View className="mt-4 flex-row gap-3">{[['Sessions',speaking.data?.stats.sessions??0],['Minutes',speaking.data?.stats.totalMinutes??0],['Avg score',`${speaking.data?.stats.averageScore??0}%`]].map(([label,value])=><View key={String(label)} className="flex-1 rounded-2xl border border-white bg-white/85 p-3"><Text className="text-xl font-extrabold text-[#10233f]">{value}</Text><Text className="mt-1 text-xs text-[#718198]">{label}</Text></View>)}</View>
      <Text className="mb-3 mt-7 text-xl font-extrabold text-[#10233f]">Choose a situation</Text>
      {speaking.data?.scenarios.map((scenario)=>{const color=categoryColors[scenario.category]??'#146ef5';return <Pressable key={scenario.id} className="mb-3 flex-row items-center rounded-[25px] border border-white bg-white/90 p-4 active:opacity-80" onPress={()=>generate.mutate(scenario.id)}><View className="h-12 w-12 items-center justify-center rounded-2xl" style={{backgroundColor:`${color}18`}}><Ionicons name={scenario.category==='Travel'?'airplane-outline':scenario.category==='Career'?'briefcase-outline':scenario.category==='Meetings'?'people-outline':'chatbubbles-outline'} size={23} color={color}/></View><View className="ml-4 flex-1"><View className="flex-row items-center"><Text className="flex-1 text-base font-extrabold text-[#10233f]">{scenario.title}</Text><Text className="text-xs font-bold capitalize" style={{color}}>{scenario.level.replace('-',' ')}</Text></View><Text className="mt-1 text-sm leading-5 text-[#718198]">{scenario.description}</Text></View></Pressable>;})}
    </>:null}
    {generate.isPending?<View className="mt-10 items-center rounded-[28px] bg-white p-8"><ActivityIndicator size="large" color="#ef6c62"/><Text className="mt-4 text-lg font-extrabold text-[#10233f]">Creating a fresh speaking task…</Text><Text className="mt-2 text-center leading-6 text-[#718198]">Your coach is adapting it to your level and learning goal.</Text></View>:null}
    {generate.error&&!practice?<View className="mt-6 rounded-2xl bg-[#fff0ee] p-4"><Text className="text-center leading-6 text-[#9c3c35]">{generate.error.message}</Text><Pressable className="mt-3 items-center" onPress={reset}><Text className="font-extrabold text-[#ef6c62]">Choose another situation</Text></Pressable></View>:null}
    {practice?<>
      <View className="mt-5 rounded-[28px] bg-[#10233f] p-5"><View className="flex-row items-center"><View className="rounded-full bg-white/10 px-3 py-2"><Text className="text-xs font-extrabold text-[#8dc5ff]">{practice.scenario.category}</Text></View><Text className="ml-3 flex-1 text-right text-xs font-bold text-[#b8cce2]">Coach: {practice.coachRole}</Text></View><Text className="mt-4 text-xl font-extrabold leading-7 text-white">{practice.prompt}</Text><Text className="mt-3 leading-6 text-[#c4d3e4]">{practice.task}</Text><Pressable className="mt-4 self-start flex-row items-center rounded-full bg-white/10 px-4 py-2" onPress={()=>Speech.speak(`${practice.prompt}. ${practice.task}`,{language:'en-US',rate:0.86})}><Ionicons name="volume-high" size={18} color="#8dc5ff"/><Text className="ml-2 font-bold text-[#8dc5ff]">Listen to task</Text></Pressable></View>
      {!result?<>
        <Text className="mb-3 mt-6 text-xl font-extrabold text-[#10233f]">Useful phrases</Text><View className="rounded-[25px] border border-white bg-white/90 p-5">{practice.targetPhrases.map((item)=><View key={item.phrase} className="mb-4 last:mb-0"><Text className="font-extrabold text-[#7c5cff]">{item.phrase}</Text><Text className="mt-1 text-sm text-[#718198]">{item.meaning}</Text></View>)}</View>
        <View className="mt-4 rounded-[25px] border border-white bg-white/90 p-5"><Text className="font-extrabold text-[#10233f]">Before you speak</Text>{practice.preparationTips.map((tip)=><View key={tip} className="mt-3 flex-row"><Ionicons name="checkmark-circle" size={19} color="#18a67e"/><Text className="ml-2 flex-1 leading-5 text-[#52647b]">{tip}</Text></View>)}</View>
        <View className="mt-5 items-center rounded-[30px] bg-[#ffe8e4] p-6"><View className={`h-24 w-24 items-center justify-center rounded-full ${recorderState.isRecording?'bg-[#e3483e]':'bg-[#ef6c62]'}`}><Pressable className="h-full w-full items-center justify-center" disabled={evaluate.isPending} onPress={recorderState.isRecording?stopRecording:startRecording}>{evaluate.isPending?<ActivityIndicator color="white"/>:<Ionicons name={recorderState.isRecording?'stop':'mic'} size={38} color="white"/>}</Pressable></View><Text className="mt-4 text-lg font-extrabold text-[#10233f]">{evaluate.isPending?'Transcribing and coaching…':recorderState.isRecording?`Recording · ${Math.floor(recorderState.durationMillis/1000)}s`:'Tap to start speaking'}</Text><Text className="mt-1 text-center text-sm text-[#7e6764]">{recorderState.isRecording?'Tap stop when your answer is complete.':'Aim for 30–90 seconds. A quiet place gives better transcription.'}</Text>{recordingError||evaluate.error?<Text className="mt-3 text-center font-semibold text-[#a33d36]">{recordingError??evaluate.error?.message}</Text>:null}</View>
        <View className="mt-4 rounded-2xl bg-white/70 p-4"><Pressable onPress={()=>Speech.speak(practice.sampleAnswer,{language:'en-US',rate:0.84})}><Text className="font-bold text-[#146ef5]">Need help? Listen to a model answer</Text></Pressable></View>
      </>:null}
      {result?<>
        <View className="mt-5 items-center rounded-[28px] bg-[#e7f8f2] p-6"><Text className="text-xs font-extrabold uppercase tracking-wider text-[#18a67e]">Speaking result</Text><Text className="mt-2 text-5xl font-extrabold text-[#126e58]">{result.overallScore}%</Text><Text className="mt-2 text-center leading-6 text-[#377462]">{result.feedback}</Text></View>
        <View className="mt-4 flex-row flex-wrap gap-y-2"><Score label="Grammar" value={result.grammarScore} color="#18a67e"/><Score label="Vocabulary" value={result.vocabularyScore} color="#7c5cff"/><Score label="Fluency" value={result.fluencyScore} color="#146ef5"/><Score label="Relevance" value={result.relevanceScore} color="#e6a01d"/></View>
        <View className="mt-4 rounded-[25px] bg-white p-5"><Text className="text-lg font-extrabold text-[#10233f]">What we heard</Text><Text className="mt-3 leading-6 text-[#52647b]">{result.transcript}</Text></View>
        <View className="mt-4 rounded-[25px] bg-white p-5"><Text className="text-lg font-extrabold text-[#10233f]">A clearer version</Text><Text className="mt-3 leading-6 text-[#40546d]">{result.correctedAnswer}</Text><Pressable className="mt-3 flex-row items-center" onPress={()=>Speech.speak(result.correctedAnswer,{language:'en-US',rate:0.84})}><Ionicons name="volume-high" size={19} color="#146ef5"/><Text className="ml-2 font-bold text-[#146ef5]">Listen</Text></Pressable></View>
        <View className="mt-4 rounded-[25px] bg-white p-5"><Text className="font-extrabold text-[#18a67e]">Strengths</Text>{result.strengths.map((item)=><View key={item} className="mt-3 flex-row"><Ionicons name="checkmark-circle" size={18} color="#18a67e"/><Text className="ml-2 flex-1 leading-5 text-[#52647b]">{item}</Text></View>)}<Text className="mt-5 font-extrabold text-[#e35d55]">Improve next</Text>{result.improvements.map((item)=><View key={item} className="mt-3 flex-row"><Ionicons name="arrow-up-circle" size={18} color="#e35d55"/><Text className="ml-2 flex-1 leading-5 text-[#52647b]">{item}</Text></View>)}</View>
        <View className="mt-4 rounded-2xl bg-[#fff3d9] p-4"><Text className="font-extrabold text-[#8a6115]">Next practice tip</Text><Text className="mt-2 leading-6 text-[#7b6740]">{result.nextTip}</Text></View><Pressable className="mb-4 mt-5 items-center rounded-2xl bg-[#ef6c62] py-4" onPress={reset}><Text className="font-extrabold text-white">Practice another situation</Text></Pressable>
      </>:null}
    </>:null}
  </ScrollView></SafeAreaView>;
}