ALTER TABLE "vocabulary" ADD COLUMN "hindi_meaning" text DEFAULT 'अर्थ उपलब्ध नहीं' NOT NULL;

INSERT INTO "vocabulary" ("word", "meaning", "hindi_meaning", "pronunciation", "part_of_speech", "simple_explanation", "example", "office_example", "synonyms", "antonyms", "level", "category", "status") VALUES
('appreciate','to recognize the value of something','सराहना करना','uh-PREE-shee-ayt','verb','To be thankful for something.','I appreciate your help.','I appreciate your quick response.',ARRAY['value','admire','recognize'],ARRAY['disregard'],'elementary','Daily Conversation','published'),
('delighted','very pleased or happy','बहुत प्रसन्न','dih-LY-tid','adjective','Feeling very happy about something.','I am delighted to meet you.','We are delighted with the results.',ARRAY['pleased','thrilled','glad'],ARRAY['disappointed'],'intermediate','Daily Conversation','published'),
('suggest','to offer an idea for consideration','सुझाव देना','suh-JEST','verb','To tell someone an idea they could try.','Can you suggest a good restaurant?','I suggest moving the meeting to Monday.',ARRAY['recommend','propose','advise'],ARRAY['discourage'],'elementary','Daily Conversation','published'),
('convenient','easy and suitable for a situation','सुविधाजनक','kuhn-VEEN-yuhnt','adjective','Something that fits your needs or time.','Is six o’clock convenient for you?','Please choose a convenient meeting time.',ARRAY['suitable','handy','practical'],ARRAY['inconvenient'],'intermediate','Daily Conversation','published'),
('deadline','the latest time work must be finished','अंतिम समय-सीमा','DED-line','noun','The final date or time for a task.','The deadline is Friday.','We must meet the project deadline.',ARRAY['due date','cutoff','time limit'],ARRAY[]::text[],'elementary','Office & Meetings','published'),
('clarify','to make something easier to understand','स्पष्ट करना','KLAIR-uh-fy','verb','To explain something more clearly.','Could you clarify your question?','Let me clarify the project requirements.',ARRAY['explain','simplify','elucidate'],ARRAY['confuse'],'intermediate','Office & Meetings','published'),
('collaborate','to work together with others','सहयोग करना','kuh-LAB-uh-rayt','verb','To work with someone toward one goal.','We collaborated on the presentation.','Our teams will collaborate on this project.',ARRAY['cooperate','partner','team up'],ARRAY['compete'],'intermediate','Office & Meetings','published'),
('priority','something more important than other things','प्राथमिकता','pry-OR-uh-tee','noun','The task that should be handled first.','Health is my priority.','Customer safety is our top priority.',ARRAY['importance','preference','precedence'],ARRAY['triviality'],'intermediate','Office & Meetings','published'),
('destination','the place someone is travelling to','गंतव्य','des-tuh-NAY-shuhn','noun','The place where a journey ends.','Paris is our final destination.','Please confirm your destination.',ARRAY['endpoint','location','goal'],ARRAY['origin'],'elementary','Travel','published'),
('reservation','an arrangement to keep a seat or room','आरक्षण','rez-er-VAY-shuhn','noun','A booking made before you arrive.','I have a hotel reservation.','Your reservation is confirmed.',ARRAY['booking','appointment','arrangement'],ARRAY['cancellation'],'elementary','Travel','published'),
('departure','the act or time of leaving','प्रस्थान','dih-PAR-cher','noun','When a person or vehicle leaves.','Our departure is at noon.','Check the departure board for updates.',ARRAY['leaving','exit','takeoff'],ARRAY['arrival'],'intermediate','Travel','published'),
('explore','to travel around and discover a place','खोज करना','ik-SPLOR','verb','To look around and learn about somewhere.','We explored the old city.','Use your free day to explore the area.',ARRAY['discover','investigate','tour'],ARRAY['ignore'],'elementary','Travel','published'),
('anxious','worried or nervous about something','चिंतित','ANGK-shuhs','adjective','Feeling worried about what may happen.','I feel anxious before interviews.','She was anxious about the presentation.',ARRAY['worried','nervous','uneasy'],ARRAY['calm'],'intermediate','Feelings','published'),
('confident','sure about your ability or decision','आत्मविश्वासी','KON-fuh-duhnt','adjective','Believing that you can succeed.','She feels confident speaking English.','I am confident in our plan.',ARRAY['assured','certain','self-reliant'],ARRAY['insecure'],'elementary','Feelings','published'),
('frustrated','annoyed because something is difficult','निराश और परेशान','FRUS-tray-tid','adjective','Feeling upset when progress is blocked.','I felt frustrated by the delay.','The customer sounded frustrated.',ARRAY['annoyed','discouraged','irritated'],ARRAY['satisfied'],'intermediate','Feelings','published'),
('relieved','happy because a worry has ended','राहत महसूस करना','rih-LEEVD','adjective','Feeling better after danger or worry passes.','I was relieved to hear the news.','We felt relieved when the issue was fixed.',ARRAY['reassured','comforted','relaxed'],ARRAY['worried'],'intermediate','Feelings','published'),
('device','a tool or machine made for a purpose','उपकरण','dih-VYSE','noun','A piece of electronic equipment.','This device tracks my steps.','Restart your device before calling support.',ARRAY['gadget','tool','equipment'],ARRAY[]::text[],'elementary','Technology','published'),
('efficient','working well without wasting time','कुशल','ih-FISH-uhnt','adjective','Doing a task quickly with little waste.','This method is more efficient.','The new software makes our work efficient.',ARRAY['effective','productive','streamlined'],ARRAY['inefficient'],'intermediate','Technology','published'),
('update','to make something more current','अद्यतन करना','UP-dayt','verb','To add the newest information or version.','Please update the application.','I will update the report this afternoon.',ARRAY['refresh','revise','upgrade'],ARRAY['downgrade'],'elementary','Technology','published'),
('secure','protected from danger or unauthorized access','सुरक्षित','sih-KYOOR','adjective','Safe and protected.','Keep your password secure.','We use a secure connection.',ARRAY['safe','protected','guarded'],ARRAY['vulnerable'],'intermediate','Technology','published'),
('analyze','to study something carefully','विश्लेषण करना','AN-uh-lyze','verb','To examine details to understand something.','We analyzed the survey results.','Please analyze the monthly data.',ARRAY['examine','evaluate','inspect'],ARRAY['ignore'],'intermediate','Study & Academic','published'),
('concept','an idea or principle','अवधारणा','KON-sept','noun','A general idea used to understand a topic.','This concept is easy to understand.','The lesson introduces a new concept.',ARRAY['idea','notion','principle'],ARRAY[]::text[],'intermediate','Study & Academic','published'),
('evidence','facts that show something is true','प्रमाण','EV-ih-duhns','noun','Information used to support a conclusion.','There is evidence for the claim.','Support your answer with evidence.',ARRAY['proof','data','indication'],ARRAY['disproof'],'intermediate','Study & Academic','published'),
('summarize','to state the main points briefly','संक्षेप में बताना','SUM-uh-ryze','verb','To give a short version of important ideas.','Please summarize the article.','Can you summarize today’s discussion?',ARRAY['condense','outline','recap'],ARRAY['expand'],'intermediate','Study & Academic','published')
ON CONFLICT ("word", "level") DO NOTHING;